---
- name: installing agents
  hosts: localhost
  gather_facts: false

# ServiceNow passes true as a string

  tasks:
  - name: monitoring agent
    debug:
      msg: Installing monitoring agent
    when: monitoring == "true"

  - name: backup agent
    debug:
      msg: Installing backup agent
    when: backup == "true"
