---
- name: compliance job
  hosts: all
  ignore_errors: true
  tasks:
  - name: Getting SELinux status
    setup:
      filter: ansible_selinux

  - name: Display SELinux status
    debug:
      msg: Host {{ ansible_hostname }} is problematic because SELinux is {{ ansible_selinux.mode }} while configuration expects {{ ansible_selinux.config_mode }}
    when: ansible_selinux.mode != "enforcing"

  - name: Check ownership of /opt/secure
    file:
      path: /opt/secure
      mode: 0700
      owner: root
