---
- name: compliance job
  hosts: all
  ignore_errors: true
  tasks:
  - name: Getting SELinux status
    setup:
      filter: ansible_selinux

  - name: Check SELinux status
    command: setenforce
    when: ansible_selinux.status != "enforcing"

  - name: Check ownership of /opt/secure
    file:
      path: /opt/secure
      mode: 0700
      owner: root
