---
- name: simple EDA reaction
  hosts: localhost
  gather_facts: false


  tasks:
  - name: get event.name from json
    set_fact:
      json_out: "{{ payload | json_query('eventData.\"event.name\"') }}"
  
  - name: display event.name
    debug:
      msg: The problem is a {{ json_out }}
