---
- name: simple EDA reaction
  hosts: localhost
  gather_facts: false

  tasks:
  - name: display full payload
    debug:
      var: payload
      
  - name: get "event.name" from json
    set_fact:
      json_out: "{{ payload | json_query('eventData.\"event.name\"[].value') }}"
  
  - name: display event.name
    debug:
      var: json_out
