---
- name: simple EDA reaction
  hosts: localhost
  gather_facts: false

  # Dynatrace sends a payload with dotted keys in their JSON payload
  # While this is JSON compliant, Ansible struggles parsing keys with dots..
  # We need to work around that with set_fact and the json_query filter for any concerned variables

  tasks:
  - name: get event.name from json
    set_fact:
      problem_type: "{{ payload | json_query('eventData.\"event.name\"') }}"
      problem_start: "{{ payload | json_query('eventData.\"event.start\"') }}"
      
  - name: display event.name
    debug:
      msg: The problem is a {{ problem_type }} on {{ payload.eventData.root_cause_entity_name }} and started at {{ problem_start }}
