---
- name: simple EDA reaction
  hosts: localhost
  gather_facts: false

  vars:
    json_var: "{{ payload }}"

  tasks:
  - name: get event.name from json
    set_fact:
      json_out: "{{ json_var | json_query('payload.eventData.\"event.name\"') }}"
  
  - name: display event.name
    debug:
      msg: The problem is a {{ json_out }}
