---
- name: pretending to failover an SAP cluster
  hosts: all
  gather_facts: true
  tasks:
  - ansible.builtin.lineinfile:
      path: /etc/ansible/facts.d/sap.fact
      regexp: 'STATUS="active"'
      line: 'STATUS="passive"'
    when: ansible_facts['ansible_local']['sap']['status'] == "active"
  - ansible.builtin.lineinfile:
      path: /etc/ansible/facts.d/sap.fact
      regexp: 'STATUS="passive"'
      line: 'STATUS="active"'
    when: ansible_facts['ansible_local']['sap']['status'] == "passive"
