---
- name: install Apache Web Server
  hosts: all
  gather_facts: false
  vars:
    remove: false
  tasks:
  - name: Requested to install Apache
    block:
      - name: Install package
        ansible.builtin.dnf:
          name: httpd
          state: present
      - name: Create firewall rule
        ansible.posix.firewalld:
          service: http
          permanent: yes
          state: enabled
          immediate: yes
    when: remove == false

  - name: Requested to remove Apache
    block:
      - name: Remove package
        ansible.builtin.dnf:
          name: httpd
          state: absent
      - name: Remove firewall rule
        ansible.posix.firewalld:
          service: http
          permanent: yes
          state: absent
          immediate: yes
    when: remove == true
