---
- name: install Apache Web Server
  hosts: all
  gather_facts: false
  vars:
    remove: false
  tasks:
  - name: Install Apache
    dnf:
      name: httpd
      state: present
    when: remove == false
  - name: Remove Apache
    dnf:
      name: httpd
      state: absent
    when: remove == true
