---
- name: install Apache Web Server
  hosts: all
  gather_facts: false
  vars:
    remove: false
  tasks:
  - name: Install Apache
    block:
      - dnf:
          name: httpd
          state: present
      - ansible.posix.firewalld:
          port: 80/tcp
          permanent: yes
          state: enabled
          immediate: yes
    when: remove == false

  - name: Remove Apache
    block:
      - dnf:
          name: httpd
          state: absent
      - ansible.posix.firewalld:
          port: 80/tcp
          permanent: yes
          state: enabled
          immediate: yes
    when: remove == true
