---
- name: Display info pulled from the CMDB
  hosts: all

  gather_facts: false

  tasks:
  - name: Display cluster info about the node
    debug:
      msg: According to Netbox CMDB I'm a VM in {{ cluster }} on {{ cluster_type }} and my role is {{ device_roles[0] }}
    when: is_virtual == True

  - name: Display tenant
    debug:
      msg: I belong to tenant {{ tenants[0] }}

  - name: Check if more than 4GB of RAM
    debug:
      msg: This machine has more than 4GB of RAM
    when: memory > 4096