---
- name: Kill a specific process
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Kill process by name
      shell: "kill -9 {{ process_name }}"
      ignore_errors: yes
      register: kill_result

    - name: Show kill command result
      debug:
        var: kill_result
