---
- name: First line support playbook
  hosts: "{{ name_of_machine }}"
  gather_facts: true
  tasks:
  - name: Restart service
    ansible.builtin.service:
      name: "{{ name_of_service }}"
      state: restarted
    register: output

  - name: Successfully restarted
    debug:
      msg: Service {{ name_of_service }} has been restarted on {{ name_of_machine }}.
    when: output.failed == false
  
  - name: Escalation L2
    debug:
      msg: Looks like something went wrong. Please escalate to L2.
    when: output.failed == true
