---
- name: First line support playbook
  hosts: "{{ name_of_machine }}"
  gather_facts: true
  become: true

  tasks:
  - name: Restart service
    ansible.builtin.service:
      name: "{{ name_of_service }}"
      state: restarted
    register: output
    ignore_errors: true

  - name: Successfully restarted
    debug:
      msg: Service {{ name_of_service }} has been restarted on {{ name_of_machine }}.
    when: output.failed == false

  - name: Escalation required
    fail:
      msg: Something failed. Please escalate to L2 support.
    when: output.failed == true
