---
- name: Simple task
  hosts: all

  gather_facts: false

  vars:
    job1_result: succeed

  tasks:
  - debug:
      msg: Hello. You requested this task to SUCCEED because you set the variable to {{ job1_result }}
    when: "job1_result.startswith('succ')"

  - fail:
      msg: Hello. You requested this task to FAIL because you set the variable to {{ job1_result }}
    when: "job1_result.startswith('fail')"
