---
- name: test connectivity to Windows machines
  hosts: all
  gather_facts: false
  tasks:
  - name: check connectivity
    win_ping:

  - name: Restart a service
    win_service:
      name: spooler
      state: restarted
