- name: check the requested OS
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Windows
    fail:
      msg: You requested a Windows machine
    when: operating_system == "windows"

  - name: Linux
    debug:
      msg: You requested a Linux machine
    when: operating_system == "linux"
