- name: check the requested OS
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Windows
    fail:
      msg: You requested a Windows machine (not judging, I still love you)
    when: operating_system == "windows"

  - name: Linux
    debug:
      msg: You requested a Red Hat Enterprise Linux machine (great choice!)
    when: operating_system == "rhel"

  - name: this playbook generates info to be used later
    ansible.builtin.set_fact:
      choice: "was great"
      one_list:
        - bananas
        - are
        - my
        - favorite
        - fruit
    when: operating_system == "rhel"
